# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[bot_api_secret]
# 平台端的密钥配置部分，此处的值若意外出现在发送的消息中，机器人会尝试拦截。但请务必提防泄露。
jwt_secret = "<Replace me with str value>" # 内置 API 的认证密钥，随意填写即可。

[bot_api]
# 平台端的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
enable = true # 是否启用此平台。
api_port = 5000 # API 服务的端口号。
